[tool.poetry]
name = "email-classification"
version = "0.1.0"
description = ""
authors = ["Iana Kasimova"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = "^2.1.1"
fasttext = {git = "https://github.com/cfculhane/fastText"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
