[tool.poetry]
name = "email-classification"
version = "0.1.0"
description = ""
authors = ["Iana Kasimova"]
readme = "README.md"
packages = [{include = "email_classification"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
