FROM python:3.11-slim

ARG YOUR_ENV

ENV YOUR_ENV=${YOUR_ENV} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.5.1

RUN apt-get update
RUN apt-get install build-essential -y

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /workspace
COPY ../pyproject.toml ../poetry.lock /workspace/

# Disabling virtual environment creation and Installing project dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev

# Now, we copy our entire project
COPY ../script/ /workspace
